### ISSUE TITLE
Generated man pages may not contain Unicode characters

### ISSUE THREAD

**Issue by glts** [Perl-Toolchain-Gang/Module-Build#9]
Perl POD documentation may be encoded in UTF-8 encoding provided that an `=encoding UTF-8` directive is present. The Pod::Man module is able to handle such documentation if the 'utf8' flag is set:

```
use Pod::Man;
my $parser = Pod::Man->new(section => 3, utf8 => 1);
$parser->parse_from_file('lib/MyModule.pm', 'mymodule.3');
```

As far as I can see, in Module::Build::Base#manify_lib_pods (https://github.com/Perl-Toolchain-Gang/Module-Build/blob/master/lib/Module/Build/Base.pm#L3268) it isn't possible to specify the encoding. Man pages produced from UTF-8-encoded POD documentation will thus always appear broken.

**Comment by trizen** [comment]
This bug still seems to be present in latest versions of MB, as `utf8 => 1` option is not passed to Pod::Man when building and installing a package.

`Data::Dump`-ing the content of `%podman_args` that is passed to `Pod::Man` (at line 3265 in Module::Build::Base: https://github.com/Perl-Toolchain-Gang/Module-Build/blob/master/lib/Module/Build/Base.pm#L3265), shows only:

```perl
{ section => 3 }
```
even though the pod file is marked as utf8, using `=encoding utf8`.

One example to reproduce the issue is: [Math/AnyNum.pod](https://metacpan.org/source/TRIZEN/Math-AnyNum-0.28/lib/Math/AnyNum.pod)
